#encoding:utf8

from keywords import HTTP as http


http.post('http://www.testingedu.com.cn/inter/HTTP/auth','')
http.assertequals('status','200')
http.savejson('token','token')
http.addheader('token','{token}')
http.post('http://www.testingedu.com.cn/inter/HTTP/login','username=Tester&password=123456')
http.assertequals('status','200')
http.savejson('userid','id')
http.post('http://www.testingedu.com.cn/inter/HTTP/getUserInfo','id={id}')
http.assertequals('status','200')
http.post('http://www.testingedu.com.cn/inter/HTTP/logout','')
http.assertequals('status','200')

http.post('http://www.testingedu.com.cn/inter/HTTP/auth','')
http.assertequals('status','200')
http.savejson('token','token')
http.addheader('token','{token}')
http.post('http://www.testingedu.com.cn/inter/HTTP/login','username=Tester&password=123456')
http.assertequals('status','200')
http.savejson('userid','id')
http.post('http://www.testingedu.com.cn/inter/HTTP/getUserInfo','id={id}')
http.assertequals('status','200')
http.post('http://www.testingedu.com.cn/inter/HTTP/logout','')
http.assertequals('status','200')

http.post('http://www.testingedu.com.cn/inter/HTTP/auth','')
http.assertequals('status','200')
http.savejson('token','token')
http.addheader('token','{token}')
http.post('http://www.testingedu.com.cn/inter/HTTP/login','username=Tester&password=123456')
http.assertequals('status','200')
http.savejson('userid','id')
http.post('http://www.testingedu.com.cn/inter/HTTP/getUserInfo','id={id}')
http.assertequals('status','200')
http.post('http://www.testingedu.com.cn/inter/HTTP/logout','')
http.assertequals('status','200')

http.post('http://www.testingedu.com.cn/inter/HTTP/auth','')
http.assertequals('status','200')
http.savejson('token','token')
http.addheader('token','{token}')
http.post('http://www.testingedu.com.cn/inter/HTTP/login','username=Tester&password=123456')
http.assertequals('status','200')
http.savejson('userid','id')
http.post('http://www.testingedu.com.cn/inter/HTTP/getUserInfo','id={id}')
http.assertequals('status','200')
http.post('http://www.testingedu.com.cn/inter/HTTP/logout','')
http.assertequals('status','200')

http.post('http://www.testingedu.com.cn/inter/HTTP/auth','')
http.assertequals('status','200')
http.savejson('token','token')
http.addheader('token','{token}')
http.post('http://www.testingedu.com.cn/inter/HTTP/login','username=Tester&password=123456')
http.assertequals('status','200')
http.savejson('userid','id')
http.post('http://www.testingedu.com.cn/inter/HTTP/getUserInfo','id={id}')
http.assertequals('status','200')
http.post('http://www.testingedu.com.cn/inter/HTTP/logout','')
http.assertequals('status','200')

http.post('http://www.testingedu.com.cn/inter/HTTP/auth','')
http.assertequals('status','200')
http.savejson('token','token')
http.addheader('token','{token}')
http.post('http://www.testingedu.com.cn/inter/HTTP/login','username=Tester&password=123456')
http.assertequals('status','200')
http.savejson('userid','id')
http.post('http://www.testingedu.com.cn/inter/HTTP/getUserInfo','id={id}')
http.assertequals('status','200')
http.post('http://www.testingedu.com.cn/inter/HTTP/logout','')
http.assertequals('status','200')

http.post('http://www.testingedu.com.cn/inter/HTTP/auth','')
http.assertequals('status','200')
http.savejson('token','token')
http.addheader('token','{token}')
http.post('http://www.testingedu.com.cn/inter/HTTP/login','username=Tester&password=123456')
http.assertequals('status','200')
http.savejson('userid','id')
http.post('http://www.testingedu.com.cn/inter/HTTP/getUserInfo','id={id}')
http.assertequals('status','200')
http.post('http://www.testingedu.com.cn/inter/HTTP/logout','')
http.assertequals('status','200')

http.post('http://www.testingedu.com.cn/inter/HTTP/auth','')
http.assertequals('status','200')
http.savejson('token','token')
http.addheader('token','{token}')
http.post('http://www.testingedu.com.cn/inter/HTTP/login','username=Tester&password=123456')
http.assertequals('status','200')
http.savejson('userid','id')
http.post('http://www.testingedu.com.cn/inter/HTTP/getUserInfo','id={id}')
http.assertequals('status','200')
http.post('http://www.testingedu.com.cn/inter/HTTP/logout','')
http.assertequals('status','200')